--1. BANKING MANAGEMENT SYSTEM. Write a PL/SQL block to CONVERT THE SALARY ACCOUNT TYPE TO SAVINGS ACCOUNT FOR THE GIVEN CUSTOMER ID.
BEGIN
    UPDATE ACCOUNT_INFO_2611
    SET account_type='SAVINGS'
    WHERE account_type='SALARY'AND CUSTOMER_ID='&ID';
END;

BEGIN
    UPDATE ACCOUNT_INFO_2611
    SET account_type='SALARY'
    WHERE  CUSTOMER_ID='&ID' AND account_type='SAVINGS';
END;

select * from account_info_2611;
--2. BMS - TO CHANGE THE IFSC OF  ICICI OF TNAGAR
BEGIN
    UPDATE BANK_INFO_2611
    SET IFSC_CODE = 'ICITN0456'
    WHERE BRANCH_NAME = 'TNAGAR'
    AND BANK_NAME='ICICI';
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('RECORD UPDATED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND');
    END IF;
END;

--3. WRITE A BLOCK TO INITIATE FUND TRANSFER FOR USER TO BENEFICIARY USER. 

--4. WRITE A BLOCK WHO AVAILS DISCOUNT BASED ON TRANSACTION ON SAME BANKING TRANSACTIONS

--5. WRITE A BLOCK TO LIST THE SENIOR CITIZEN - ACCOUNT HOLDERS 
DECLARE
    CURSOR C1 IS 
        SELECT CUSTOMER_ID 
        FROM ACCOUNT_INFO_2611 WHERE TO_CHAR(ACTIVATION_DATE,'YYYY')+10<=TO_CHAR(SYSDATE,'YYYY') ;
    V_ID CUSTOMER_PERSONAL_INFO_2611.CUSTOMER_ID%TYPE;
BEGIN
    OPEN C1;
    LOOP
        FETCH C1 INTO V_ID;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_ID);
    END LOOP;
   CLOSE C1;
END;

--select TO_CHAR(ACTIVATION_DATE,'YYYY') from ACCOUNT_INFO_2611;  
--select TO_CHAR(ACTIVATION_DATE,'YYYY')+10 from ACCOUNT_INFO_2611; 
--select TO_CHAR(SYSDATE,'YYYY') from ACCOUNT_INFO_2611;  
--SELECT * FROM ACCOUNT_INFO_2611 WHERE TO_CHAR(ACTIVATION_DATE,'YYYY')+10>=TO_CHAR(SYSDATE,'YYYY');

--6. WRITE A BLOCK TO CHANGE THE ACCOUNT HOLDERS BRANCH.(INCLUDING IFSC) FOR THE GIVEN ACCOUNT HOLDER
BEGIN
    UPDATE ACCOUNT_INFO_2611
    SET IFSC_CODE = 'ICITN0456'
    WHERE CUSTOMER_ID='&ID';
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('RECORD UPDATED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND');
    END IF;
END;

--7. WRITE A BLOCK TO CHECK THE ACCOUNT HOLDER NAME AND TO ADD THE NOMIEE NAME 
--FOR THE SENIOR CITIZEN - AFTER 10 YEARS OF ACCOUNT OPENING YEAR
--(EXTRACT SENIOR CITIZEN LIST,
--EXTRACT THE YEAR OF ACCOUNT OPENING,
--CREATE TABLE TO MAP NOMINEE NAME AND SENIOR CITIZEN PK,
--ADD THE NOMINEE NAME)
--8. DISPLAY THE NAME OF THE EMPLOYEE AND THE NUMBER OF RECORDS USING CURSOR AND CURSOR LOOP
DECLARE
    CURSOR C1 IS 
        SELECT EMPLOYEE_ID id,FIRST_NAME 
        FROM employees_2611_ ;
    V_ID employees_2611_.EMPLOYEE_ID%TYPE;
    V_NAME employees_2611_.FIRST_NAME%TYPE;
    COUNT_EMP NUMBER(10):=0;
BEGIN
    OPEN C1;
    LOOP
        FETCH C1 INTO V_ID,V_NAME;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_ID||' '||V_NAME);
        COUNT_EMP:=COUNT_EMP+1;
    END LOOP;
      DBMS_OUTPUT.PUT_LINE('NO OF ROWS IN THE TABLE = ' ||COUNT_EMP);
    CLOSE C1;
END;

--9. Write a procedure to increase the salary of all the employees by 5000 using FORALL.
CREATE or replace PROCEDURE adjust_salary33
(
    in_employee_id IN EMPLOYEES_2611_.EMPLOYEE_ID%TYPE
) IS
BEGIN
   UPDATE employees_2611_
   SET salary = salary +  5000
   WHERE employee_id = in_employee_id;
END;
--
--SELECT * FROM employees_2611_;
----24075
---- call procedure
--exec adjust_salary33(102);
---- after adjustment
--SELECT * FROM employees_2611_;

--BEGIN
--   UPDATE employees_2611_
--   SET salary = salary +  100
--   WHERE employee_id = '&id';
--END;

CREATE OR REPLACE PROCEDURE inc_salary_2611
IS
CURSOR CUR IS
SELECT EMPLOYEE_ID FROM XX_EMPL_2608;
TYPE emp_id_type IS TABLE OF XX_EMPL_2608.EMPLOYEE_ID%TYPE;
emp_id_list emp_id_type;
BEGIN
OPEN CUR;
FETCH CUR BULK COLLECT INTO emp_id_list;
FORALL indx IN emp_id_list.FIRST..emp_id_list.LAST
UPDATE XX_EMPL_2608 SET SALARY=SALARY+5000 WHERE EMPLOYEE_ID=emp_id_list(indx);
CLOSE CUR;
END;